# Generated by Django 4.2.3 on 2023-07-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='users/default_profile_picture.svg', null=True, upload_to='users/profile_picture'),
        ),
    ]
